# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://docs.travis-ci.com/user/ci-environment/
# trusty - 7.5GB memory and 2 cores
sudo: required
dist: trusty

# travis performs a shallow clone by default, in case of any issues
# that requires full git history, enable this
# before_install: git fetch --unshallow

# parallel builds on jdk7 and jdk8
language: java
jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

env:
  MAVEN_SKIP_RC=true
  MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512M"

# workaround added: https://github.com/travis-ci/travis-ci/issues/4629
before_install:
  - |
    if [[ ! -e $HOME/.thrift/bin/thrift ]]; then
      sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libboost-filesystem-dev libboost-thread-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
      wget https://www.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
      tar xfz thrift-0.9.3.tar.gz
      cd thrift-0.9.3 && ./configure --without-cpp --without-c_glib --without-python --without-ruby --without-php --without-erlang --without-go --without-nodejs -q --prefix=$HOME/.thrift
      sudo make install > thrift_make_install.log
      cd ..
    fi
  - |
    if [[ ! -e /usr/local/bin/thrift ]]; then
      sudo ln -s $HOME/.thrift/bin/thrift /usr/local/bin/thrift
    fi
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml


install: true

script: mvn clean install -DskipTests -T 4 -q -Pitests
